services:
  invokeai:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HSA_OVERRIDE_GFX_VERSION: 11.0.0
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    ports:
      - 9090:9090
    volumes:
      - ~/invokeai:/invokeai